// client/src/Pages/Details.jsx
import React, { useEffect, useState } from 'react'
import { useParams } from "react-router-dom";

export const Details = () => {
    let { id } = useParams();
    console.log(id)
 
    const apiKey = '669aaaeebc2c443dad9cb08436de8d23';
    const apiUrl = `https://api.spoonacular.com/recipes/${id}/information?includeNutrition=false&apiKey=${apiKey}`;
    const [data, setData] = useState([])
    useEffect(() => {
        fetch(apiUrl).then((e) => {
            return e.json()
        }).then((r) => {
            setData(r)
        })

    }, [])


    console.log(data)
    return (
        <>
            <div key={data && data.id}>
                <img src={data && data.image} alt="Recipe Image" />
                <h3>{data && data.title}</h3>
                <p>{data && data.summary}</p>
                <p>{data && data.instructions}</p>
            </div>

        </>
    )
}

// client/src/views/Details.vue
<template>
  <div v-if="data">
    <img :src="data.image" alt="Recipe Image" />
    <h3>{{ data.title }}</h3>
    <p v-html="data.summary"></p>
    <p v-if="data.instructions" v-html="data.instructions"></p>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'

type RecipeDetails = {
  id: number
  image: string
  title: string
  summary?: string
  instructions?: string
}

const route = useRoute()
const data = ref<RecipeDetails | null>(null)

onMounted(async () => {
  const id = route.params.id as string
  const apiKey = '4af02576760d4266b2534701bd32f8f9'
  const apiUrl = `https://api.spoonacular.com/recipes/${id}/information?includeNutrition=false&apiKey=${apiKey}`
  const res = await fetch(apiUrl)
  data.value = await res.json()
})
</script>
